version: '3.8'

services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-my-blazor-app-default}:latest 
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blazor-ui.entrypoints=web"
      - "traefik.http.routers.blazor-ui.rule=PathPrefix(`/`)"
      - "traefik.http.services.blazor-ui-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-net"
      - "traefik.http.routers.blazor-ui.priority=1"
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    ports:
      - "8881:8880"
      - "8090:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"      
      - "./traefik-config.yml:/etc/traefik/traefik.yml:roo"
    networks:
      - proxy-net 



networks: 
  proxy-net:
    external: true