version: '3.8'

services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-my-blazor-app-default}:latest 
    restart: unless-stopped
    ports:
      - "8080:80"
