api:
  dashboard: true 
  insecure: true 

entryPoints:
  web:
    address: ":8880" 

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy-net

log:
  level: DEBUG

accessLog: {}